In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [10]:
c = np.array([2,3,4,5,6,7]).reshape(2,3)
c
# reshape created 2 rows with 3 numbers
# it does not reshape if there are more or less numbers. It fills in as excact

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
e = np.array([1, 2, 3, 4, 5, 6])
print("The sum is",e.sum()) # Sum the array
print("The min is",e.min()) # Find the minimum value in an array
print("The max is",e.max()) # Find the maximum value in an array
print("The mean is",e.mean()) # Find the arithmetic mean of an array
# no need to place a space after the statement, does it for you.

The sum is 21
The min is 1
The max is 6
The mean is 3.5


In [14]:
np.zeros(5) # Creates an array of zeros with 5 elements
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000. Maybe useful in A/B testing
np.arange(25) # Like the "Range" function we learned earlier, this is gives you a range of integers between 1 - 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])